"""initial migration

Revision ID: 90965c1a62f0
Revises: 
Create Date: 2026-03-03 01:33:38.500689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90965c1a62f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_details', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('purchase_details', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('purchase_details', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_constraint(op.f('purchase_details_purchase_id_fkey'), 'purchase_details', type_='foreignkey')
    op.drop_constraint(op.f('purchase_details_product_id_fkey'), 'purchase_details', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_details', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'purchase_details', 'purchases', ['purchase_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('purchases_supplier_id_fkey'), 'purchases', type_='foreignkey')
    op.drop_constraint(op.f('purchases_user_id_fkey'), 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'suppliers', ['supplier_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'purchases', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.add_column('suppliers', sa.Column('logo', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'suppliers', ['email'])
    op.create_unique_constraint(None, 'suppliers', ['rfc'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_column('suppliers', 'logo')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key(op.f('purchases_user_id_fkey'), 'purchases', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('purchases_supplier_id_fkey'), 'purchases', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'purchase_details', type_='foreignkey')
    op.drop_constraint(None, 'purchase_details', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_details_product_id_fkey'), 'purchase_details', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('purchase_details_purchase_id_fkey'), 'purchase_details', 'purchases', ['purchase_id'], ['id'])
    op.alter_column('purchase_details', 'expiration_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('purchase_details', 'updated_at')
    op.drop_column('purchase_details', 'created_at')
    # ### end Alembic commands ###
