from fastapi import Depends
from ..utils.security import require_permission


def can(permission: str) -> list:
    """Lista de dependencias para proteger un endpoint con un permiso."""
    return [Depends(require_permission(permission))]


def _crud(resource: str) -> tuple:
    """(read, create, update, delete) para un recurso."""
    return tuple(can(f"{resource}.{action}") for action in ("read", "create", "update", "delete"))


CAN_READ_USERS, CAN_CREATE_USERS, CAN_UPDATE_USERS, CAN_DELETE_USERS = _crud("users")
CAN_READ_BRANCHES, CAN_CREATE_BRANCHES, CAN_UPDATE_BRANCHES, CAN_DELETE_BRANCHES = _crud("branches")
CAN_READ_PERMISSIONS, CAN_CREATE_PERMISSIONS, CAN_UPDATE_PERMISSIONS, CAN_DELETE_PERMISSIONS = _crud("permissions")
CAN_READ_ROLES, CAN_CREATE_ROLES, CAN_UPDATE_ROLES, CAN_DELETE_ROLES = _crud("roles")
CAN_READ_PRODUCTS, CAN_CREATE_PRODUCTS, CAN_UPDATE_PRODUCTS, CAN_DELETE_PRODUCTS = _crud("products")
CAN_READ_PRODUCT_CATEGORIES, CAN_CREATE_PRODUCT_CATEGORIES, CAN_UPDATE_PRODUCT_CATEGORIES, CAN_DELETE_PRODUCT_CATEGORIES = _crud("productscategories")
CAN_READ_SALES, CAN_CREATE_SALES, CAN_UPDATE_SALES, CAN_DELETE_SALES = _crud("sales")
CAN_READ_SALE_PAYMENTS, CAN_CREATE_SALE_PAYMENTS, CAN_UPDATE_SALE_PAYMENTS, CAN_DELETE_SALE_PAYMENTS = _crud("salepayments")
CAN_READ_SALE_DETAILS, CAN_CREATE_SALE_DETAILS, CAN_UPDATE_SALE_DETAILS, CAN_DELETE_SALE_DETAILS = _crud("saledetails")
CAN_READ_REFUND_PRODUCTS, CAN_CREATE_REFUND_PRODUCTS, CAN_UPDATE_REFUND_PRODUCTS, CAN_DELETE_REFUND_PRODUCTS = _crud("refundproducts")
CAN_READ_SUPPLIERS, CAN_CREATE_SUPPLIERS, CAN_UPDATE_SUPPLIERS, CAN_DELETE_SUPPLIERS = _crud("suppliers")
CAN_READ_PURCHASES, CAN_CREATE_PURCHASES, CAN_UPDATE_PURCHASES, CAN_DELETE_PURCHASES = _crud("purchases")
CAN_READ_PURCHASE_DETAILS, CAN_CREATE_PURCHASE_DETAILS, CAN_UPDATE_PURCHASE_DETAILS, CAN_DELETE_PURCHASE_DETAILS = _crud("purchasedetails")
CAN_READ_PRODUCT_BATCHES, CAN_CREATE_PRODUCT_BATCHES, CAN_UPDATE_PRODUCT_BATCHES, CAN_DELETE_PRODUCT_BATCHES = _crud("productbatches")
CAN_READ_SALE_BATCH_USAGES, CAN_CREATE_SALE_BATCH_USAGES, CAN_UPDATE_SALE_BATCH_USAGES, CAN_DELETE_SALE_BATCH_USAGES = _crud("salebatchusages")
CAN_READ_PRODUCT_MASTERS, CAN_CREATE_PRODUCT_MASTERS, CAN_UPDATE_PRODUCT_MASTERS, CAN_DELETE_PRODUCT_MASTERS = _crud("productmasters")
CAN_READ_PRODUCT_BRANDS, CAN_CREATE_PRODUCT_BRANDS, CAN_UPDATE_PRODUCT_BRANDS, CAN_DELETE_PRODUCT_BRANDS = _crud("productbrands")
CAN_READ_INGREDIENTS, CAN_CREATE_INGREDIENTS, CAN_UPDATE_INGREDIENTS, CAN_DELETE_INGREDIENTS = _crud("ingredients")
CAN_READ_SENSOR_READINGS, CAN_CREATE_SENSOR_READINGS, CAN_UPDATE_SENSOR_READINGS, CAN_DELETE_SENSOR_READINGS = _crud("sensorreadings")
CAN_READ_ANIMAL_GROUPS, CAN_CREATE_ANIMAL_GROUPS, CAN_UPDATE_ANIMAL_GROUPS, CAN_DELETE_ANIMAL_GROUPS = _crud("animalgroups")
CAN_READ_GENERA, CAN_CREATE_GENERA, CAN_UPDATE_GENERA, CAN_DELETE_GENERA = _crud("genera")
CAN_READ_SPECIES, CAN_CREATE_SPECIES, CAN_UPDATE_SPECIES, CAN_DELETE_SPECIES = _crud("species")
CAN_READ_MORPHS, CAN_CREATE_MORPHS, CAN_UPDATE_MORPHS, CAN_DELETE_MORPHS = _crud("morphs")
CAN_READ_ANIMALS, CAN_CREATE_ANIMALS, CAN_UPDATE_ANIMALS, CAN_DELETE_ANIMALS = _crud("animals")
CAN_READ_ARTICLES, CAN_CREATE_ARTICLES, CAN_UPDATE_ARTICLES, CAN_DELETE_ARTICLES = _crud("articles")

CAN_READ_DASHBOARD = can("dashboard.read")
